#%RAML 1.0 Trait
responses:
  400:
    body:
      application/json:
        type: !include ../Types/errorMessageOutputType.raml
        example: !include ../Examples/400-error-message-output-example.json
  403:
    body:
      application/json:
        type: !include ../Types/errorMessageOutputType.raml
        example: !include ../Examples/403-error-message-output-example.json
  404:
    body:
      application/json:
        type: !include ../Types/errorMessageOutputType.raml
        example: !include ../Examples/404-error-message-output-example.json
  405:
    body:
      application/json:
        type: !include ../Types/errorMessageOutputType.raml
        example: !include ../Examples/405-error-message-output-example.json
  406:
    body:
      application/json:
        type: !include ../Types/errorMessageOutputType.raml
        example: !include ../Examples/406-error-message-output-example.json
  408:
    body:
      application/json:
        type: !include ../Types/errorMessageOutputType.raml
        example: !include ../Examples/408-error-message-output-example.json
  409:
    body:
      application/json:
        type: !include ../Types/errorMessageOutputType.raml
        example: !include ../Examples/409-error-message-output-example.json
  415:
    body:
      application/json:
        type: !include ../Types/errorMessageOutputType.raml
        example: !include ../Examples/415-error-message-output-example.json
  429:
    body:
      application/json:
        type: !include ../Types/errorMessageOutputType.raml
        example: !include ../Examples/429-error-message-output-example.json
  500:
    body:
      application/json:
        type: !include ../Types/errorMessageOutputType.raml
        example: !include ../Examples/500-error-message-output-example.json
  501:
    body:
      application/json:
        type: !include ../Types/errorMessageOutputType.raml
        example: !include ../Examples/501-error-message-output-example.json
  502:
    body:
      application/json:
        type: !include ../Types/errorMessageOutputType.raml
        example: !include ../Examples/502-error-message-output-example.json
  503:
    body:
      application/json:
        type: !include ../Types/errorMessageOutputType.raml
        example: !include ../Examples/503-error-message-output-example.json
  504:
    body:
      application/json:
        type: !include ../Types/errorMessageOutputType.raml
        example: !include ../Examples/504-error-message-output-example.json